### ISSUE TITLE
IngenieríaEnSoftware-Infografía-DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/actividad-1-infografia-g00gle2401#2]
[Ingeniería de software-Infografía-DiegoAlexisCarlosCruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-g00gle2401/files/9420117/Ingenieria.de.software-Infografia-DiegoAlexisCarlosCruz.pdf)

**Comment by mel-16** [comment]
Solo Utilizo una Referencia 
Cal: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
